version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

configuration:
  templates:
    - name: python3-http
      source: https://github.com/openfaas-incubator/python-flask-template

functions:
  botopush:
    lang: python3-http
    handler: ./botopush
    image: theaxer/botopush:latest
    requests:
      memory: 40Mi
    environment:
      AWS_SHARED_CREDENTIALS_FILE: "/var/openfaas/secrets/botopush-aws"
      bucket: botopush-example
    secrets:
      - botopush-aws
